version: "3.9"
services:
  frontend:
    container_name: posco-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    networks:
      - default
    labels:
      - traefik.enable=true

      # Router para http
      - traefik.http.routers.posco-frontend-http.entrypoints=http
      - traefik.http.routers.posco-frontend-http.rule=Host(`localhost.dev.com`)

      # Router para https
      - traefik.http.routers.posco-frontend-https.entrypoints=https
      - traefik.http.routers.posco-frontend-https.rule=Host(`localhost.dev.com`)
      - traefik.http.routers.posco-frontend-https.tls=true

  backend:
    container_name: posco-backend
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - default
    labels:
      - traefik.enable=true

      - traefik.http.routers.posco-backend-http.entrypoints=http
      - traefik.http.routers.posco-backend-http.rule=Host(`localhost.dev.com`) && PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)

      - traefik.http.routers.posco-backend-https.entrypoints=https
      - traefik.http.routers.posco-backend-https.rule=Host(`localhost.dev.com`) && PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)
      - traefik.http.routers.posco-backend-https.tls=true

  db:
    image: postgres
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    logging:
      driver: "none"

    networks:
      - default

volumes:
  app-db-data:
