version: "3.9"
services:
  frontend:
    container_name: posco-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      # Router para http
      - traefik.http.routers.posco-frontend-http.entrypoints=http
      - traefik.http.routers.posco-frontend-http.rule=Host(`${DOMAIN}`)

      # Router para https
      - traefik.http.routers.posco-frontend-https.entrypoints=https
      - traefik.http.routers.posco-frontend-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.posco-frontend-https.tls=true
      - traefik.http.routers.posco-backend-https.tls.certresolver=le

      # Enable redirection for HTTP and HTTPS
      - traefik.http.routers.posco-backend-http.middlewares=https-redirect

  backend:
    container_name: posco-backend
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.routers.posco-backend-http.entrypoints=http
      - traefik.http.routers.posco-backend-http.rule=Host(`api.${DOMAIN}`)

      - traefik.http.routers.posco-backend-https.entrypoints=https
      - traefik.http.routers.posco-backend-https.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.posco-backend-https.tls=true
      - traefik.http.routers.posco-backend-https.tls.certresolver=le

      # Enable redirection for HTTP and HTTPS
      - traefik.http.routers.posco-backend-http.middlewares=https-redirect

  db:
    image: postgres:12
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  app-db-data:

networks:
  traefik-public:
    # Allow setting it to false for testing
    external: true
